### ISSUE TITLE
rng.lua

### ISSUE THREAD

**Issue by GBEY0402** [AlanWarren/gearswap#4]
hard time trying to set ranged tp set or melee tp set based on weapons equiped.

**Comment by AlanWarren** [comment]
Mote's libs provide a few different ways you could achieve this.  My lua is already handling ranged weapon based sets with `CombatWeapon`.  All you have to do is make sure your ranged weapon is listed in the rng_rema list for sets.midcast.RA.WeaponName to work.  

If you want to create named sets for melee weapons in addition to ranged, then you'll need to use a different dynamic set.  CombatForm, CustomRangedGroups, and CustomMeleeGroups are already being used, but you could use CustomClass. 

i.e. 
```lua
function get_combat_weapon()
    state.CombatWeapon:reset()
    if rng_rema:contains(player.equipment.range) then
        state.CombatWeapon:set(player.equipment.range)
    end
   -- put your melee weapon logic here  
    classes.CustomClass = player.equipment.main
end
```
Pay attention to set order.  Mote's libs enforce this for sets.engaged.  
`sets.engaged.[CombatForm][CombatWeapon][Offense or HybridMode][CustomMeleeGroups or CustomClass]`

closing this since it's a basic coding question with regards to using Mote's library, and not necessarily an issue with my lua.

**Comment by GBEY0402** [comment]
Its ok, as a dev i completly redo your script. No offense. Think about using more global variables to not run the while code to change a piece of equipment.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by AlanWarren** [comment]
I call BS.  I can tell you have no idea how this code works, and you didn't spend anytime at all studying the interface. Otherwise you wouldn't have had _any trouble_ getting named sets working.  Why try and feint having knowledge? 

 I'll admit this isn't the most elegant piece of code out there.  It's the standard RNG.lua the library author provides with some "nice things" added by myself 6 years ago.  Everything done here is per the libraries design.  

I'm a senior software engineer, so go ahead.  Try explaining how your changes prevent a while loop from executing.  I'd love to see it.
